backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/public/images" # Media files will be stored in the repo under images

collections:
 - name: "projects"
   label: "Projetos"
   folder: "/public/posts"
   create: true
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:
    - {label: "Nome", name: "projectname", widget: "string"}
    - {label: "Texto", name: "texto", widget: "markdown"}